name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: T1
      id: t1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: T1
        setup-command: ''
        command: python3 solution.py
        input: |-
          3
          6
        expected-output: '9'
        comparison-method: exact
        timeout: 10
        max-score: 2
    - name: T2
      id: t2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: T2
        setup-command: ''
        command: python3 solution.py
        input: |-
          7
          8
        expected-output: '15'
        comparison-method: exact
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T1_RESULTS: "${{steps.t1.outputs.result}}"
        T2_RESULTS: "${{steps.t2.outputs.result}}"
      with:
        runners: t1,t2
    - name: Debug T1 Result
      run: |
        echo "T1 Result: ${{steps.t1.outputs.result}}"

